baseURL: https://lukas-lbs.netlify.app/
languageCode: en-us
title: Portfolio - Lukas Kugler
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: View contents
    subtitle: |-
    title: Portfolio - Lukas Kugler
  blog: {Lukas Kugler}
  contact:
    address:
      - city: London
        country: United Kingdom
        street: Regents Park
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: lkugler.mfa2022@london.edu
        title: Email
    enable: yes
    phone:
      - phone: Please enquire for phone number
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Lukas Kugler
    enable: yes
    quicklinks:
    social:
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/lukas.kglr/
      - icon: fa-github
        label: GitHub
        url: https://github.com/Lukas-LBS
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/lkugler-lbs/
  image: ''
  name: Lukas Kugler
  navigation:
    button1:
      - name: R-projects
        url: blogs
    links:
      - name: Home
        url: '#'
#      - name: R-projects
#        url: blogs
      - name: About me
        url: blogs/aboutme
#      - name: Elements
#        url: elements.html
    menu: Menu
    subtitle:
    title: Lukas Kugler
  tiles:
    enable: yes
    showcase:
      - image: Picture1.png
        subtitle: Short introduction about this blog and its owner
        title: About me
        url: blogs/aboutme
      - image: melissa-bradley-iwiAxOuJw-unsplash.jpg
        subtitle: How did the climate change over time?
        title: Climate Change
        url: blogs/climate
      - image: mmmmmm.jpg
        subtitle: How do rentals of Boris Bikes change over time?
        title: Boris Bikes
        url: blogs/bike
      - image: denise-jans-tV80374iytg-unsplash.jpg
        subtitle: How are movie returns achieved?
        title: Movies, cast facebook likes, budgets, and returns
        url: blogs/movies
      - image: pic05.jpg
        subtitle: Ipsum Dolor Sit Amet
        title: hike
        url: blogs/hike
      - image: pic06.jpg
        subtitle: Feugiat Amet Tempus
        title: Etiam
        url: blogs/ipsum
  two:
    buttonText: R-projects
    enable: yes
    subtitle:
    title: Find out more about my a(R)twork
    url: blogs
